# Generated by Django 5.2.7 on 2025-11-03 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('medical_certificate', models.FileField(upload_to='doctor_docs/medical_certificates/')),
                ('qualification', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('designation', models.CharField(choices=[('Consultant', 'Consultant'), ('Resident', 'Resident'), ('Surgeon', 'Surgeon')], max_length=50)),
                ('registration_certificate', models.FileField(upload_to='doctor_docs/registration_certificates/')),
                ('degree_certificates', models.FileField(upload_to='doctor_docs/degree_certificates/')),
                ('aadhaar', models.FileField(upload_to='doctor_docs/aadhaar/')),
                ('passport_photo', models.ImageField(upload_to='doctor_docs/passport_photos/')),
                ('experience_certificate', models.FileField(blank=True, null=True, upload_to='doctor_docs/experience_certificates/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='hospitals.hospital')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.treatment')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
