# Generated by Django 5.2.7 on 2025-11-27 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_doctor_status'),
        ('hospitals', '0009_alter_hospital_hospital_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='hospitals.department'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='treatments',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='hospitals.treatment'),
        ),
    ]
