# Generated by Django 5.2.7 on 2025-11-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_doctor_department_doctor_treatments'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='Doctor Name', max_length=255),
        ),
    ]
