# Generated by Django 5.2.7 on 2025-11-21 10:30

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='availability_status',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='opd_timings',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='timing',
        ),
        migrations.RemoveField(
            model_name='hospitaladminprofile',
            name='registration_number',
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='aadhaar',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='degree_certificates',
            field=models.FileField(upload_to=accounts.models.doctor_cert_path),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='experience_certificate',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.doctor_cert_path),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='medical_certificate',
            field=models.FileField(upload_to=accounts.models.doctor_cert_path),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='passport_photo',
            field=models.ImageField(upload_to=accounts.models.doctor_photo_path),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='registration_certificate',
            field=models.FileField(upload_to=accounts.models.doctor_cert_path),
        ),
    ]
