# Generated by Django 5.2.7 on 2025-11-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaladminprofile',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
