# Generated by Django 5.2.7 on 2025-11-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_hospitaladminprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='aadhaar',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
