# Generated by Django 5.2.7 on 2025-12-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_doctorprofile_aadhaar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='aadhaar',
            field=models.CharField(max_length=20),
        ),
    ]
