# Generated by Django 5.2.7 on 2025-12-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_delete_patient_remove_appointment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='slot_duration',
            field=models.IntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (45, '45 minutes'), (60, '60 minutes')], default=30, help_text='Duration of each appointment slot in minutes'),
        ),
    ]
