# Generated by Django 5.2.7 on 2026-01-08 07:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_cancellation_reason_and_more'),
        ('doctors', '0010_doctor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('current_token', models.PositiveIntegerField(default=0)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_queues', to='doctors.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'date')},
            },
        ),
    ]
