# Generated by Django 5.2.7 on 2026-01-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_dailyqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='patient_reports/'),
        ),
    ]
