# Generated by Django 5.2.7 on 2026-01-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_appointment_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
