# Generated by Django 5.2.7 on 2026-01-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text="The term the user searches for (e.g., 'heart pain')", max_length=100)),
                ('mapped_term', models.CharField(help_text="The medical term to map to (e.g., 'Cardiology')", max_length=100)),
            ],
        ),
    ]
