# Generated by Django 3.2.25 on 2026-01-07 13:35

from django.db import migrations, models
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=patients.models.patient_photo_path),
        ),
    ]
