# Generated by Django 5.2.7 on 2025-11-05 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitaladmin',
            old_name='hospital',
            new_name='Hospital',
        ),
        migrations.AlterField(
            model_name='hospitaladmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='hospitaladmin',
            table=None,
        ),
    ]
