# Generated by Django 5.2.7 on 2025-11-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_remove_hospitaladmin_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
        migrations.AddField(
            model_name='hospital',
            name='state',
            field=models.CharField(default='Gujarat', max_length=50),
        ),
    ]
