# Generated by Django 5.2.7 on 2025-11-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_hospital_country_hospital_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_type',
            field=models.CharField(choices=[('general', 'General'), ('multispeciality', 'Multispeciality')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hours',
            field=models.CharField(default='9:00 AM - 5:00 PM', max_length=100),
        ),
    ]
