# Generated by Django 5.2.7 on 2025-11-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_hospital_hospital_type_hospital_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
