# Generated by Django 5.2.7 on 2025-11-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_hospital_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospital_type',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hours',
            field=models.JSONField(default=dict),
        ),
    ]
