# Generated by Django 5.2.7 on 2025-11-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_alter_hospital_hospital_type_alter_hospital_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospital_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
