# Generated by Django 5.2.7 on 2025-11-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0008_alter_hospital_hospital_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospital_type',
            field=models.JSONField(default=list),
        ),
    ]
