# Generated by Django 3.2.25 on 2026-01-07 13:35

from django.db import migrations, models
import hospitals.models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0009_alter_hospital_hospital_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=hospitals.models.hospital_logo_path),
        ),
    ]
