# Generated by Django 5.2.7 on 2026-02-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0010_alter_hospital_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(default='GEN', max_length=10),
        ),
    ]
