
import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'revana_hms.settings')
django.setup()

from django.contrib.auth import get_user_model
from hospitals.models import HospitalAdmin
from doctors.models import Doctor
from patients.models import Patient

User = get_user_model()

def export_users():
    filename = "user_credentials.md"
    
    with open(filename, "w") as f:
        f.write("# 🔐 User Credentials List\n\n")
        f.write("> **Note:** This list contains active users generated by the population scripts.\n\n")

        # 1. Hospital Admins
        admins = HospitalAdmin.objects.select_related('user', 'hospital').all()
        f.write(f"## 🏥 Hospital Admins ({admins.count()})\n")
        f.write("**Default Password:** `admin123`\n\n")
        f.write("| Email (Username) | Hospital | City |\n")
        f.write("| :--- | :--- | :--- |\n")
        for a in admins:
            city = a.hospital.city if a.hospital else "N/A"
            h_name = a.hospital.name if a.hospital else "Unassigned"
            f.write(f"| `{a.user.email}` | {h_name} | {city} |\n")
        f.write("\n---\n\n")

        # 2. Doctors
        doctors = Doctor.objects.select_related('user', 'hospital', 'department').filter(is_approved=True)
        f.write(f"## 👨‍⚕️ Doctors ({doctors.count()})\n")
        f.write("**Default Password:** `doctor123`\n\n")
        f.write("| Email (Username) | Name | Specialization | Hospital |\n")
        f.write("| :--- | :--- | :--- | :--- |\n")
        for d in doctors:
            dept = d.department.name if d.department else d.specialization
            h_name = d.hospital.name if d.hospital else "N/A"
            f.write(f"| `{d.user.email}` | {d.name} | {dept} | {h_name} |\n")
        f.write("\n---\n\n")

        # 3. Patients
        patients = Patient.objects.select_related('user').all().order_by('-id')
        f.write(f"## 👤 Patients ({patients.count()})\n")
        f.write("**Default Password:** `patient123`\n\n")
        f.write("| Email (Username) | Name | Age | Gender |\n")
        f.write("| :--- | :--- | :--- | :--- |\n")
        for p in patients:
            f.write(f"| `{p.user.email}` | {p.name} | {p.age} | {p.gender} |\n")
    
    print(f"Successfully exported users to {filename}")

if __name__ == "__main__":
    export_users()
